# Generated by Django 3.2 on 2023-11-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=200)),
                ('theater_image', models.ImageField(upload_to='images/')),
                ('owner_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('manager_name', models.CharField(max_length=200)),
                ('approved', models.BooleanField(default=True)),
            ],
        ),
    ]
