# Generated by Django 3.2 on 2023-11-29 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminboscoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='password',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='username',
        ),
        migrations.AddField(
            model_name='theater',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
