# Generated by Django 3.2 on 2023-11-30 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminboscoapp', '0002_auto_20231129_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_trailer', models.FileField(blank=True, null=True, upload_to='movies/trailers/')),
                ('movie_rdate', models.DateField(blank=True, null=True)),
                ('movie_des', models.TextField()),
                ('movie_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('movie_poster', models.ImageField(default='movies/poster/not.jpg', upload_to='movies/poster')),
                ('movie_genre', models.CharField(default='Action | Comedy | Romance', max_length=50)),
                ('movie_duration', models.CharField(default='2hr 45min', max_length=10)),
                ('theater_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminboscoapp.theater')),
            ],
        ),
    ]
