# Generated by Django 3.2 on 2023-12-01 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminboscoapp', '0003_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_show', to='adminboscoapp.movie')),
                ('theater_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminboscoapp.theater')),
            ],
        ),
    ]
