# Generated by Django 3.2 on 2023-12-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboscoapp', '0004_shows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
